### ISSUE TITLE
首页大图可以浏览视频，视频是放在内容页中的

### ISSUE THREAD

**Issue by Natt7** [uicestone/TheMaker#40]

**Comment by JennieJi** [comment]
视频是放在内容页中的是什么逻辑？
1 首页大图跟内容页视频比例不一样
2 你如果有很多内容页有视频，你哪个放首页？
然后声明一点，首页大图是滚动播放图片跟内容页直接插入视频不一样。在滚动播放过程中切换下一张或者上一张图片是要额外写代码停止视频。要播放视频也就代表原先的隔几秒滚动播放图片要修改为手动切换或者悬停效果。因为设计稿中并未体现有视频，所以属于CR需要多一些时间完成并额外收费。
